import Link from "next/link";
import DemandAssistanceEntry from "../../../components/portal/DemandAssistanceEntry";
import { getForm26AS, getOutstandingDemand, getProcessingResult, getTaxPayment } from "../../../data/mock";
import { formatAssessmentYear, formatIndianCurrency, formatIndianDate, formatRecordLabel } from "../../../lib/format-tax";

export default function DemandDetailPage() {
  const demand = getOutstandingDemand(); const payment = getTaxPayment(); const form26asEntry = getForm26AS().entries[0]; const processing = getProcessingResult();
  return <div className="professional-demand">
    <Link className="back-link" href="/pending-actions">← Pending Actions</Link>
    <header className="demand-page-header"><div><p className="eyebrow">Pending action <span aria-hidden="true">·</span> AY {formatAssessmentYear(demand.assessmentYear)}</p><h1>Outstanding Demand</h1><p>Income Tax records show an outstanding amount requiring your response.</p></div><div className="demand-page-header__amount"><strong>{formatIndianCurrency(demand.amount, demand.currency)}</strong><span>Response pending</span></div></header>
    <section className="professional-section" aria-labelledby="demand-details-title"><div className="professional-section__heading"><div><p className="eyebrow">Government record</p><h2 id="demand-details-title">Demand details</h2></div><span className="demand-status"><span className="ux4g-badge-icon-warning ux4g-badge-m" aria-hidden="true">!</span><strong>{formatRecordLabel(demand.status)}</strong></span></div><dl className="compact-details"><div><dt>Assessment Year</dt><dd>{formatAssessmentYear(demand.assessmentYear)}</dd></div><div><dt>Outstanding amount</dt><dd>{formatIndianCurrency(demand.amount, demand.currency)}</dd></div><div><dt>Demand status</dt><dd>Response pending</dd></div><div><dt>Created on</dt><dd>{formatIndianDate(demand.createdOn)}</dd></div><div><dt>Demand reference</dt><dd>{demand.demandId}</dd></div><div><dt>Processing reference</dt><dd>{demand.processingId}</dd></div></dl></section>
    <section className="professional-section" aria-labelledby="related-records-title"><div className="professional-section__heading"><div><p className="eyebrow">Tax information</p><h2 id="related-records-title">Related tax records</h2></div></div><div className="related-record-table" role="table" aria-label="Records related to this outstanding demand"><div className="related-record-table__head" role="row"><span role="columnheader">Record</span><span role="columnheader">Date / reference</span><span role="columnheader">Amount</span><span role="columnheader">Status</span><span role="columnheader"><span className="visually-hidden">Action</span></span></div><div role="row"><span role="cell"><strong>Self-Assessment Tax</strong><small>Payment</small></span><span role="cell">{formatIndianDate(payment.paymentDate)}<small>{payment.challanReference}</small></span><span role="cell">{formatIndianCurrency(payment.amount, payment.currency)}</span><span role="cell">{formatRecordLabel(payment.status)}</span><span role="cell"><Link href="/payments">View payment</Link></span></div><div role="row"><span role="cell"><strong>Form 26AS</strong><small>Self-Assessment Tax</small></span><span role="cell">{formatIndianDate(form26asEntry.paymentDate)}<small>{form26asEntry.challanReference}</small></span><span role="cell">{formatIndianCurrency(form26asEntry.amount, form26asEntry.currency)}</span><span role="cell">{formatRecordLabel(form26asEntry.status)}</span><span role="cell"><Link href="/payments/form-26as">View Form 26AS</Link></span></div><div role="row"><span role="cell"><strong>Processed return</strong><small>Tax credit recognised</small></span><span role="cell">{formatIndianDate(processing.processedOn)}<small>{processing.processingId}</small></span><span role="cell">{formatIndianCurrency(processing.selfAssessmentTaxRecognised, processing.currency)}</span><span role="cell">{formatRecordLabel(processing.status)}</span><span role="cell"><Link href="/returns">View return</Link></span></div></div></section>
    <section className="professional-section demand-manual-actions" aria-labelledby="manual-actions-title"><div className="professional-section__heading"><div><p className="eyebrow">Manual services</p><h2 id="manual-actions-title">Actions</h2></div></div><div className="manual-action-layout"><div><h3>Respond to this demand</h3><p>Choose a conventional Income Tax action.</p><div className="action-row"><Link className="ux4g-btn ux4g-btn-primary ux4g-btn-md" href="/pending-actions/demand/respond">Respond to demand</Link><Link className="ux4g-btn ux4g-btn-outline-primary ux4g-btn-md" href="/pending-actions/demand/pay">Pay demand</Link></div></div><div className="related-service"><p className="eyebrow">Related service</p><h3>Correct tax-credit details</h3><p>Tax Credit Mismatch Correction</p><Link className="ux4g-text-link-md" href="/services">Open service</Link></div></div><DemandAssistanceEntry /></section>
  </div>;
}
