import Link from "next/link";
import PageHeading from "../../../components/portal/PageHeading";
import RecordDetails from "../../../components/portal/RecordDetails";
import DemandAssistanceEntry from "../../../components/portal/DemandAssistanceEntry";
import { getOutstandingDemand, getProcessingResult } from "../../../data/mock";
import { formatAssessmentYear, formatIndianCurrency, formatIndianDate, formatRecordLabel } from "../../../lib/format-tax";
export default function DemandDetailPage() {
  const demand = getOutstandingDemand(); const processing = getProcessingResult();
  return <><PageHeading eyebrow="Pending action" title="Outstanding Demand" description="Income Tax records show an outstanding amount requiring your response." backHref="/pending-actions" backLabel="Pending Actions" />
    <section className="demand-overview" aria-labelledby="demand-amount-title"><div><p className="eyebrow">Amount outstanding</p><h2 id="demand-amount-title" className="demand-amount">{formatIndianCurrency(demand.amount, demand.currency)}</h2></div><span className="demand-status"><span className="ux4g-badge-icon-warning ux4g-badge-m" aria-hidden="true">!</span><strong>{formatRecordLabel(demand.status)}</strong></span></section>
    <section className="record-section" aria-labelledby="demand-details-title"><div className="section-heading"><div><p className="eyebrow">Government record</p><h2 id="demand-details-title">Demand details</h2></div></div><div className="ux4g-card ux4g-card-outline ux4g-card-vertical"><div className="ux4g-card-body"><RecordDetails details={[{ label: "Assessment Year", value: formatAssessmentYear(demand.assessmentYear) }, { label: "Demand status", value: "Response pending" }, { label: "Created on", value: formatIndianDate(demand.createdOn) }, { label: "Demand reference", value: demand.demandId }, { label: "Processing reference", value: demand.processingId }, { label: "Record source", value: formatRecordLabel(demand.source) }]} /></div></div></section>
    <section className="record-section" aria-labelledby="processing-context-title"><div className="section-heading"><div><p className="eyebrow">Processing context</p><h2 id="processing-context-title">Processed return information</h2></div></div><div className="ux4g-card ux4g-card-outline ux4g-card-vertical"><div className="ux4g-card-body"><RecordDetails details={[{ label: "Processing status", value: formatRecordLabel(processing.status) }, { label: "Processed date", value: formatIndianDate(processing.processedOn) }, { label: "Processing reference", value: processing.processingId }]} /></div></div></section>
    <section className="government-actions" aria-labelledby="government-actions-title"><h2 id="government-actions-title">Respond to this demand</h2><p>Choose a conventional Income Tax action.</p><div className="action-row"><Link className="ux4g-btn ux4g-btn-outline-primary ux4g-btn-md" href="/pending-actions/demand/pay">Pay now</Link><Link className="ux4g-btn ux4g-btn-primary ux4g-btn-md" href="/pending-actions/demand/respond">Submit response</Link></div><DemandAssistanceEntry /></section>
  </>;
}
