import PageHeading from "../../components/portal/PageHeading";
import RecordDetails from "../../components/portal/RecordDetails";
import CaseAwareDemandProgress from "../../components/portal/CaseAwareDemandProgress";
import { getOutstandingDemand } from "../../data/mock";
import { formatAssessmentYear, formatIndianCurrency, formatIndianDate, formatRecordLabel } from "../../lib/format-tax";

export default function PendingActionsPage() {
  const demand = getOutstandingDemand();
  return <><PageHeading eyebrow="Account actions" title="Pending Actions" description="Review items that require a response from you." /><section className="portal-surface demand-card" aria-labelledby="pending-demand-title"><div className="portal-surface__header demand-card__header"><div><p className="eyebrow">Outstanding Demand</p><h2 id="pending-demand-title">{formatIndianCurrency(demand.amount, demand.currency)}</h2></div><span className="portal-status portal-status--warning"><span className="portal-status__icon" aria-hidden="true">!</span><strong>{formatRecordLabel(demand.status)}</strong></span></div><div className="portal-surface__body demand-card__body"><RecordDetails details={[{ label: "Assessment Year", value: formatAssessmentYear(demand.assessmentYear) }, { label: "Created on", value: formatIndianDate(demand.createdOn) }, { label: "Government demand status", value: "Response pending" }]} /></div><div className="portal-surface__footer demand-card__footer"><CaseAwareDemandProgress fallbackHref="/pending-actions/demand" fallbackLabel="View details" /></div></section><section className="other-action-areas" aria-labelledby="other-actions-title"><div className="section-heading"><div><p className="eyebrow">Other action areas</p><h2 id="other-actions-title">More pending-action services</h2></div></div><ul><li><strong>Worklist</strong><span>No pending items</span></li><li><strong>e-Proceedings</strong><span>No pending items</span></li><li><strong>Compliance Portal</strong><span>External service</span></li></ul></section></>;
}
