import Link from "next/link";
import { ArrowDown, ArrowLeft, ArrowRight, Check, CircleAlert } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import type { DemandUnderstanding } from "@/lib/ai";
import { resolveUnderstandingSurface } from "@/lib/ai/understanding-surface";
import { formatIndianCurrency, formatIndianDate, formatIndianShortDate, formatRecordLabel } from "@/lib/format-tax";
import SourceTrace from "./SourceTrace";
import ImportantDates from "./ImportantDates";

export function PaymentQuestionSurface({ understanding }: { understanding: DemandUnderstanding }) { const { payment, form26as } = understanding.workflowContext.records; return <section className="question-surface"><header><p className="assistance-kicker">Your payment</p><h2>{formatIndianCurrency(payment.amount, payment.currency)} <span>{formatRecordLabel(payment.status)}</span></h2></header><dl className="question-facts"><div><dt>Payment type</dt><dd>{formatRecordLabel(payment.paymentType)}</dd></div><div><dt>Date</dt><dd>{formatIndianDate(payment.paymentDate)}</dd></div><div><dt>Challan</dt><dd>{payment.challanReference}</dd></div></dl><div className="recorded-sources"><p>Recorded in</p><span><Check aria-hidden="true" />Payment record</span><span><Check aria-hidden="true" />Form 26AS · {formatRecordLabel(form26as.entries[0].status)}</span></div><Link className={buttonVariants({ variant: "link" })} href="/payments">View payment record <ArrowRight aria-hidden="true" /></Link></section>; }

export function Form26ASQuestionSurface({ understanding }: { understanding: DemandUnderstanding }) { const record=understanding.workflowContext.records.form26as, entry=record.entries[0]; return <section className="question-surface"><header><p className="assistance-kicker">Form 26AS</p><h2>Self-Assessment Tax</h2></header><dl className="question-facts question-facts-emphasis"><div><dt>Amount</dt><dd>{formatIndianCurrency(entry.amount, entry.currency)}</dd></div><div><dt>Status</dt><dd>{formatRecordLabel(entry.status)}</dd></div><div><dt>Date</dt><dd>{formatIndianDate(entry.paymentDate)}</dd></div><div><dt>Challan</dt><dd>{entry.challanReference}</dd></div></dl><Link className={buttonVariants({ variant: "link" })} href="/payments/form-26as">View Form 26AS <ArrowRight aria-hidden="true" /></Link></section>; }

export function ReturnQuestionSurface({ understanding, onUnderstand }: { understanding: DemandUnderstanding; onUnderstand: () => void }) { const { taxReturn, processingResult, payment }=understanding.workflowContext.records; return <section className="question-surface"><header><p className="assistance-kicker">Return status</p><h2>Your return was processed</h2></header><ol className="return-sequence"><li><time>{formatIndianShortDate(taxReturn.filedOn)}</time><strong>Income Tax Return filed</strong><ArrowDown aria-hidden="true" /></li><li><time>{formatIndianShortDate(processingResult.processedOn)}</time><strong>Return processed</strong><ArrowDown aria-hidden="true" /></li><li><strong>{formatIndianCurrency(processingResult.selfAssessmentTaxRecognised, processingResult.currency)}</strong><span>Self-Assessment Tax recognised</span></li></ol><p className="question-explanation">Your payment record shows <strong>{formatIndianCurrency(payment.amount, payment.currency)}</strong>.</p><Button onClick={onUnderstand} type="button" variant="link">Understand the mismatch <ArrowRight aria-hidden="true" /></Button></section>; }

export function EvidenceQuestionSurface({ understanding }: { understanding: DemandUnderstanding }) { const resolved=resolveUnderstandingSurface(understanding.specification,understanding.evidence); return <section className="question-surface evidence-question-surface"><header><p className="assistance-kicker">Connected records</p><h2>Records used for this explanation</h2><p>These Income Tax account records support the comparison.</p></header><SourceTrace currency={understanding.evidence.currency} defaultOpen items={resolved.sourceTrace.items} /></section>; }

export function PayAgainQuestionSurface({ understanding, onNext }: { understanding: DemandUnderstanding; onNext: () => void }) { const e=understanding.evidence; return <section className="question-surface"><header><p className="assistance-kicker">Before you pay again</p><h2>Review the mismatch first</h2></header><div className="pay-again-comparison"><p><span>Payment found</span><strong>{formatIndianCurrency(e.payment.amount,e.currency)}</strong><small>{formatRecordLabel(e.payment.status)}</small></p><p><span>Processed return recognised</span><strong>{formatIndianCurrency(e.processedReturn.selfAssessmentTaxRecognised,e.currency)}</strong></p></div><p className="question-explanation">The records show the payment exists, but it was not included when the return was processed.</p><div className="question-recommendation"><CircleAlert aria-hidden="true" /><p><span>Recommended next step</span><strong>Review the tax-credit mismatch before making another payment.</strong></p></div><Button className="app-action app-action-primary" onClick={onNext} type="button">Review next step <ArrowRight aria-hidden="true" /></Button></section>; }

export function DatesQuestionSurface({ waitingForReview }: { waitingForReview: boolean }) { return <section className="question-surface dates-question-surface"><header><p className="assistance-kicker">Dates</p><h2>Dates to remember</h2><p>Synthetic case reminders, not statutory Income Tax deadlines.</p></header><ImportantDates waitingForReview={waitingForReview} /></section>; }

export function ScopeBoundarySurface({ onAsk }: { onAsk: (question:string)=>void }) { const options=["Check my payments","Explain my return","Review pending actions","Show case progress"]; return <section className="question-surface"><header><p className="assistance-kicker">Available help</p><h2>I can help with information available in this prototype account.</h2></header><div className="scope-actions">{options.map(x=><button key={x} onClick={()=>onAsk(x)} type="button">{x}<ArrowRight aria-hidden="true" /></button>)}</div></section>; }

export function NoCaseSurface({ onOverview }: { onOverview:()=>void }) { return <section className="question-surface"><header><p className="assistance-kicker">Case status</p><h2>No submitted case to track yet</h2><p>Review the outstanding demand and the current corrective action first.</p></header><Button onClick={onOverview} type="button" variant="link"><ArrowLeft aria-hidden="true" />Back to overview</Button></section>; }
